## Shortcut script for running all the data-loading scripts

## Load data
source("data-raw/achievements.R")
source("data-raw/animal_blueprints.R")
source("data-raw/animals.R")
source("data-raw/big_craftables.R")
source("data-raw/building_blueprints.R")
source("data-raw/bundles.R")
source("data-raw/caught_fish.R")
source("data-raw/complete_npc_gift_tastes.R")
source("data-raw/crops.R")
source("data-raw/crops_object_information.R")
source("data-raw/furniture.R")
source("data-raw/hats.R")
source("data-raw/locations.R")
source("data-raw/monsters.R")
source("data-raw/npc_dispositions.R")
source("data-raw/quests.R")
source("data-raw/seeds_object_information.R")
source("data-raw/weapons.R")
